config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'

  resources :ingredients
  resources :recipes
  resources :recipe_ingredients, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates_presence_of :name
  validates_uniqueness_of :name, case_sensitive: false

  has_many :recipe_ingredients, dependent: :destroy
  has_many :recipes, through: :recipe_ingredients
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates_presence_of :name

  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  def create
    @ingredient = Ingredient.new(ingredient_params)

    if @ingredient.save
      redirect_to ingredients_path, notice: 'Ingredient was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /ingredients/1
  def update
    if @ingredient.update(ingredient_params)
      redirect_to ingredients_path, notice: 'Ingredient was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /ingredients/1
  def destroy
    @ingredient.destroy
    redirect_to ingredients_path, notice: 'Ingredient was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def ingredient_params
      params.require(:ingredient).permit(:name)
    end
end

app/controllers/recipe_ingredients_controller.rb
class RecipeIngredientsController < ApplicationController
  def new
    @recipes = Recipe.all.map { |r| [r.name, r.id] }
    @ingredients = Ingredient.all.map { |i| [i.name, i.id] }
    @recipe_ingredient = RecipeIngredient.new
  end

  def create
    @recipe_ingredient = RecipeIngredient.new(recipe_ingredient_params)
    if @recipe_ingredient.save
      redirect_to :back
    else
      render :new
    end
  end

  def destroy
    recipe_ingredient = RecipeIngredient.find(params[:id])
    recipe_ingredient.destroy
    redirect_to recipe_path(recipe_ingredient.recipe_id)
  end


  private
    def recipe_ingredient_params
        params.require(:recipe_ingredient).permit(:recipe_id, :ingredient_id, :amount)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  def index
    @recipes = Recipe.all
  end

  def show
  end

  def new
    @recipe = Recipe.new
  end

  def edit
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to @recipe
    else
      render :new
    end
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_path
  end


  private
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    def recipe_params
      params.require(:recipe).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipe_ingredients_helper.rb
module RecipeIngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/ingredients/_form.html.erb
<%= form_for(ingredient) do |f| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

app/views/ingredients/index.html.erb
<h1>Ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.name %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DplRecipes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav>
      <div class="nav-wrapper">
        <a href="#!" class="brand-logo">Logo</a>
        <a href="#" data-activates="mobile" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
          <li><%= link_to 'Recipes', recipes_path %></li>
          <li><%= link_to 'Ingredients', ingredients_path %></li>
          <li><%= link_to 'Add Ing To Rec', new_recipe_ingredient_path %></li>
        </ul>
        <ul class="side-nav" id="mobile">
          <li><%= link_to 'Recipes', recipes_path %></li>
          <li><%= link_to 'Ingredients', ingredients_path %></li>
          <li><%= link_to 'Add Ing To Rec', new_recipe_ingredient_path %></li>
        </ul>
      </div>
    </nav>    
    <%= yield %>
  </body>
</html>

app/views/recipe_ingredients/new.html.erb
<h1> Add an ingredient </h1>

<%= form_for @recipe_ingredient do |f| %>
  <%= f.select :recipe_id, options_for_select(@recipes) %>
  <%= f.select :ingredient_id, options_for_select(@ingredients) %>
  <%= f.text_field :amount, required: true, placeholder: 'Amount' %>
  <%= f.submit nil, class: 'btn' %>
<% end %>

<hr />
<%= link_to 'All Recipes', recipes_path %> |
<%= link_to 'All Ingredients', ingredients_path %>

app/views/recipes/_form.html.erb
<%= form_for recipe do |f| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.name %></td>
        <td><%= recipe.description %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br />

<%= link_to 'New Recipe', new_recipe_path %> |

<%= link_to 'Add Ingredient To Recipe', new_recipe_ingredient_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

app/views/recipes/show.html.erb
<h1>Recipe: <%= @recipe.name %> </h1>

<% unless @recipe.description.empty? %>
    <p>
      <strong>Description:</strong>
      <%= @recipe.description %>
    </p>
    <hr />
<% end %>

<% if @recipe.ingredients.any? %>
    <h5> Ingredients </h5>
    <ul>
        <% @recipe.recipe_ingredients.each do |recipe_ingredient| %>
          <li>
            <%= recipe_ingredient.ingredient.name %> - <%= recipe_ingredient.amount %> -
            <%= link_to 'Remove', recipe_ingredient_path(recipe_ingredient), method: :delete, data: {confirm: 'Really remove this ingredient?'} %>
          </li>
        <% end %>
    </ul>
<% else %>
  <h5>No Ingredients Found</h5>
<% end %>

<%= link_to 'All Recipes', recipes_path %> |
<%= link_to 'Edit', edit_recipe_path(@recipe) %>